### ISSUE TITLE
Allow to specify custom style props like titleClassName

### ISSUE THREAD

**Issue by hukpo** [nderscore/prettier-plugin-nativewind#1]
Currently, all props are hardcoded to ['class', 'className', 'tw']
It would be nice to have the ability to extend them.

Thanks for the fork 🤗

**Comment by nderscore** [comment]
Thanks for the suggestion. 

I went ahead and added some options which will enable full customization of both the props and function calls being searched.

This is released in [v0.2.0](https://www.npmjs.com/package/prettier-plugin-nativewind/v/0.2.0)

You can find documentation for how to customize the props here: 
https://github.com/nderscore/prettier-plugin-nativewind#customizing-props
