### ISSUE TITLE
Fetch from upstream integration with https://github.com/ianvs/prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by OlegLustenko** [nderscore/prettier-plugin-nativewind#3]
Hey, can we include this commit also?

https://github.com/nderscore/prettier-plugin-nativewind/commit/f9b249b171003da870e6865fd2b54c226b501a97

It adds integration with https://github.com/ianvs/prettier-plugin-sort-imports

**Comment by nderscore** [comment]
Synced with upstream to `prettier-plugin-tailwindcss@0.2.5`

Released in `prettier-plugin-nativewind@0.2.1` :+1:
